from .api.utils import (
    build_definition_table,
    collapse_alleles,
    get_default_allele,
    get_function,
    get_priority,
    get_score,
    has_definition,
    has_phenotype,
    has_score,
    is_subset,
    list_alleles,
    list_functions,
    list_genes,
    list_phenotypes,
    list_variants,
    load_allele_table,
    load_diplotype_table,
    load_equation_table,
    load_gene_table,
    load_phenotype_table,
    load_variant_table,
    predict_alleles,
    predict_phenotype,
    predict_score,
)

del api
