from .api.utils import (
    build_definition_table,
    compute_control_statistics,
    compute_copy_number,
    create_consolidated_vcf,
    estimate_phase_beagle,
    get_default_allele,
    get_function,
    get_paralog,
    get_priority,
    get_region,
    get_score,
    has_definition,
    has_phenotype,
    has_score,
    list_alleles,
    list_functions,
    list_genes,
    list_phenotypes,
    list_variants,
    load_allele_table,
    load_control_table,
    load_cnv_table,
    load_diplotype_table,
    load_equation_table,
    load_gene_table,
    load_phenotype_table,
    load_variant_table,
    predict_alleles,
    predict_cnv,
    predict_phenotype,
    predict_score,
    sort_alleles,
)

from .api.plot import (
    plot_bam_copy_number,
    plot_bam_read_depth,
    plot_vcf_allele_fraction,
    plot_vcf_read_depth,
)

del api
